# Generated by Django 2.1.4 on 2020-05-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_auto_20200507_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tushare',
            name='formula',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tushare',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
